"""Reproducible PDF catalog. Hand-checked examples anchor generated edge cases.
Run from the repository root: python3 scripts/build_catalog.py
"""
import json, pathlib, io, contextlib, math, re
ROOT=pathlib.Path(__file__).resolve().parents[1]
problems=[]
COMMON='''import sys, math
from collections import Counter
raw=sys.stdin.read().strip()
tokens=raw.split()
def prime(x):
    return x>=2 and all(x%d for d in range(2,math.isqrt(x)+1))
def emit(a):
    print(' '.join(map(str,a)))
def divisors(n):
    return [x for x in range(1,n) if n%x==0]
'''
def output(code, data):
    old=__import__('sys').stdin; __import__('sys').stdin=io.StringIO(data)
    out=io.StringIO()
    try:
        with contextlib.redirect_stdout(out):exec(code, {})
    finally:__import__('sys').stdin=old
    return out.getvalue().rstrip()
def add(level,num,title,desc,body,sample,expected,cases,fmt='A single integer n.',constraints='-100000 <= n <= 100000.',outfmt='Print the result exactly as shown in the examples.',prefix='n=int(tokens[0])\n',note=''):
    code=COMMON+prefix+body+'\n'
    sample=str(sample); expected=str(expected)
    actual=output(code,sample)
    assert actual==expected,(level,num,actual,expected)
    inputs=list(dict.fromkeys([sample]+[str(c) for c in cases]))
    assert len(inputs)>=6,(level,num,'need six distinct cases')
    tests=[dict(input=v,expected_output=output(code,v),test_type='basic' if i==0 else ['valid','edge','large','special','random'][(i-1)%5],is_hidden=i>0) for i,v in enumerate(inputs)]
    legacy={1:'fibonacci-series',2:'smallest-prime-number',3:'prime-or-composite-number',4:'series-sum-calculator',5:'divisor-sum-and-equality-checker',6:'abundant-number',7:'leap-and-non-leap-years',8:'geometric-series-sum-calculator',9:'sum-of-squares-of-n-natural-numbers',10:'harmonic-series',11:'digits-count',49:'reverse-the-digits'}
    slug=legacy.get(num) if level==2 else None
    slug=slug or f'level-{level}-{num:02}-'+re.sub('[^a-z0-9]+','-',title.lower()).strip('-')
    problems.append(dict(source=f'Level {level}',source_number=num,problem_number=num if level==2 else 57+num,title=title,slug=slug,difficulty='Easy' if level==2 else 'Medium',category=f'Level {level}'+(' — Arrays' if level==3 else ' — Loops & Numbers'),tags=[f'level-{level}','array' if level==3 else 'loops'],description=f'Level {level} · Question {num}\n\n'+desc+ ('\n\nClarification: '+note if note else ''),constraints=constraints,input_format=fmt,output_format=outfmt,reference_solution=code,examples=[dict(input=sample,output=expected,explanation='Sample for the contract above.')],tests=tests))
def l2(n,title,desc,body,sample,expected,cases,**kw):add(2,n,title,desc,body,sample,expected,cases,**kw)
l2(1,'Fibonacci Series','Print the first n Fibonacci numbers starting at 0,1, with a comma after every number. For n <= 0 print Invalid Input.',"a,b=0,1\nr=[]\nfor _ in range(max(0,n)):\n    r.append(str(a)); a,b=b,a+b\nprint(','.join(r)+',' if n>0 else 'Invalid Input')",5,'0,1,1,2,3,',[0,-5,1,2,7,20,45],constraints='-100 <= n <= 45.')
l2(2,'Smallest 5 Primes Greater Than N','Print the smallest five primes strictly greater than n, one per line.',"x=n+1\nr=[]\nwhile len(r)<5:\n    if prime(x):r.append(x)\n    x+=1\nprint(*r,sep='\\n')",10,'11\n13\n17\n19\n23',[-5,0,2,99,1000,10000])
l2(3,'Prime or Composite Number','Classify n. Numbers below 2 are neither prime nor composite.',"print(f'{n} is a prime number' if prime(n) else f'{n} is a composite number' if n>=2 else f'{n} is neither prime nor composite')",7,'7 is a prime number',[12,1,0,-7,2,121,97])
l2(4,'Series Sum Calculator','Repeat digit d to form n terms (3,33,333,...). Print the series joined by " + ", then its sum on the next line.',"d,n=map(int,tokens)\na=[int(str(d)*i) for i in range(1,n+1)]\nprint(' + '.join(map(str,a)))\nprint(sum(a))",'3 4','3 + 33 + 333 + 3333\n3702',['5 3','0 1','9 1','1 9','7 4','2 5'],prefix='',fmt='Digit d, then number of terms n.',constraints='0 <= d <= 9; 1 <= n <= 9.')
l2(5,'Divisor Sum and Equality Checker','Print all positive proper divisors in ascending order, then their sum, then whether n is an equal number (sum equals n).',"a=divisors(n)\nemit(a)\nprint(sum(a))\nprint(f'{n} is an equal number' if sum(a)==n else f'{n} is not an equal number')",6,'1 2 3\n6\n6 is an equal number',[1,2,25,28,496,8128],constraints='1 <= n <= 10000.')
l2(6,'Abundant Number','Check whether the sum of proper positive divisors exceeds n.',"print(f'{n} is an Abundant number' if sum(divisors(n))>n else f'{n} is not an Abundant number')",12,'12 is an Abundant number',[1,7,28,18,24,100],constraints='1 <= n <= 10000.')
l2(7,'Count Leap and Non-Leap Years','Classify year y and count leap and non-leap years in y+1 through y+10 inclusive.',"leap=lambda y:y%400==0 or (y%4==0 and y%100!=0)\nc=sum(leap(y) for y in range(n+1,n+11))\nprint(f'{n} is a Leap Year.' if leap(n) else f'{n} is not a Leap Year.')\nprint(f'Leap Years: {c}\\nNon-Leap Years: {10-c}')",2022,'2022 is not a Leap Year.\nLeap Years: 3\nNon-Leap Years: 7',[2020,2024,1900,1996,2000,2096,2100],constraints='1 <= y <= 9990.',note='The next decade excludes the input year.')
l2(8,'Geometric Series Sum Calculator','Sum n terms of 1 + 1/2 + 1/4 + ... . For n <= 0 print 0.00. Use two decimal places.',"print(f'{sum(0.5**i for i in range(max(0,n))):.2f}')",6,'1.97',[-7,0,1,2,4,12,1000],constraints='-100 <= n <= 1000.')
l2(9,'Sum of Squares of N Natural Numbers','Sum the squares from 1 through n. For n <= 0 print Invalid input.',"print(n*(n+1)*(2*n+1)//6 if n>0 else 'Invalid input')",5,55,[0,-10,1,12,50,10000])
l2(10,'Harmonic Series Sum','Sum 1 + 1/2 + ... + 1/n to two decimals. For n <= 0 print Invalid Input.',"print(f'{sum(1/i for i in range(1,n+1)):.2f}' if n>0 else 'Invalid Input')",10,'2.93',[0,-15,1,4,61,10000])
l2(11,'Digits Count','Count decimal digits, ignoring the minus sign. Zero has one digit.',"print(len(str(abs(n))))",47580,5,[0,-234,1,-1000000000,1234567890,100],constraints='-2147483648 <= n <= 2147483647.')
floyd="k=1\nif n<=0:print('Invalid')\nelse:\n    for i in range(1,n+1):\n        emit(range(k,k+i)); k+=i"
l2(12,'Square Pattern','Print an n by n square of # characters. For n < 1 print "n is Invalid input.".',"print('\\n'.join(['#'*n]*n) if n>0 else f'{n} is Invalid input.')",3,'###\n###\n###',[0,-10,1,2,6,30],constraints='-100 <= n <= 50.')
l2(13,'Pyramid Pattern','Print consecutive integers in rows of lengths 1,2,...,n. For n <= 0 print Invalid.',floyd,3,'1\n2 3\n4 5 6',[0,-3,1,2,5,30],constraints='-100 <= n <= 50.',note='Numbers are separated by spaces, including the first three rows.')
l2(14,'Swap the Digits','Swap the first and last digits. A one-digit number is unchanged; discard leading zeros in the result.',"s=str(n)\nprint(int(s[-1]+s[1:-1]+s[0]) if len(s)>1 else n)",12345,52341,[0,7,10,100,909,109876],constraints='0 <= n <= 2147483647.')
l2(15,'Perfect Cubes','Print cubes of n,n+1,n+2, one per line. For n <= 0 print Invalid.',"print('\\n'.join(str(x**3) for x in range(n,n+3)) if n>0 else 'Invalid')",10,'1000\n1331\n1728',[0,-5,1,7,15,1000],constraints='-100 <= n <= 1000.')
l2(16,'Roman Numerals','Convert integers 1 to 40 to Roman numerals; otherwise print Invalid input.',"if not 1<=n<=40:print('Invalid input')\nelse:\n    s=''\n    for v,c in [(40,'XL'),(10,'X'),(9,'IX'),(5,'V'),(4,'IV'),(1,'I')]:\n        s+=c*(n//v); n%=v\n    print(s)",37,'XXXVII',[0,-7,1,4,9,40,41])
l2(17,'Sum of Odd and Even Numbers up to N','Print the sum of odd numbers in 1..n, then the sum of even numbers in 1..n.',"print(((n+1)//2)**2)\nprint((n//2)*(n//2+1))",5,'9\n6',[1,2,4,8,15,10000],constraints='1 <= n <= 100000.',note='The samples sum numbers up to n, not the first n odd/even terms.')
l2(18,'Detecting Narcissistic Numbers','Check whether n equals the sum of each decimal digit raised to the number of digits.',"s=str(n)\nprint(f'{n} is a narcissistic number' if sum(int(x)**len(s) for x in s)==n else f'{n} is not a narcissistic number')",153,'153 is a narcissistic number',[0,1,126,370,9474,99999],constraints='0 <= n <= 2147483647.')
l2(19,'Digit Sum Calculator','Print the sum of even digits, then the sum of odd digits. Ignore any minus sign.',"a=list(map(int,str(abs(n))))\nprint(sum(x for x in a if x%2==0))\nprint(sum(x for x in a if x%2))",123456,'12\n9',[0,5627,-2468,13579,1000,9999999999],constraints='Absolute value has at most 10 digits.')
l2(20,'Alphabet Triangle Generator','Row i contains the ith uppercase letter repeated i times. For n <= 0 print Invalid.',"print('\\n'.join(chr(64+i)*i for i in range(1,n+1)) if n>0 else 'Invalid')",3,'A\nBB\nCCC',[0,-2,1,2,6,26],constraints='-100 <= n <= 26.')
l2(21,'Finding the Next Palindrome','Find the smallest palindrome strictly greater than n.',"n+=1\nwhile str(n)!=str(n)[::-1]:n+=1\nprint(n)",123,131,[0,9,99,121,4567,99999],constraints='0 <= n <= 1000000.')
l2(22,'Finding Consecutive Palindromic Numbers','Print the first five palindromes greater than or equal to n.',"a=[]\nwhile len(a)<5:\n    if str(n)==str(n)[::-1]:a.append(n)\n    n+=1\nemit(a)",99,'99 101 111 121 131',[0,1,10,100,999,10000],constraints='0 <= n <= 1000000.',note='Include n itself when palindromic, as in the PDF sample for 99.')
l2(23,'Palindromic Right-Angled Triangle','For each row build the next i consecutive integers, then mirror them without repeating the largest. For n <= 0 print Invalid.',"k=1\nif n<=0:print('Invalid')\nelse:\n    for i in range(1,n+1):\n        a=list(range(k,k+i));emit(a+a[-2::-1]);k+=i",4,'1\n2 3 2\n4 5 6 5 4\n7 8 9 10 9 8 7',[0,-4,1,2,5,20],constraints='-100 <= n <= 30.')
l2(24,'The Palindromic Sum','Sum all palindromic positive integers <= n.',"print(sum(x for x in range(1,n+1) if str(x)==str(x)[::-1]))",10,45,[1,9,11,99,1000,100000],constraints='1 <= n <= 100000.')
mult="print('\\n'.join(' '.join(str(5*j) for j in range(1,i+1)) for i in range(1,n+1)) if n>0 else 'Invalid')"
l2(25,'Pattern Printing with Multiples of 5','Row i contains the first i positive multiples of 5. For n < 1 print Invalid.',mult,3,'5\n5 10\n5 10 15',[0,-5,1,2,6,30],constraints='-100 <= n <= 50.')
l2(26,'Squares of Even and Odd Numbers','Print squares of positive integers <= n that have the same parity as n.',"emit(x*x for x in range(1 if n%2 else 2,n+1,2))",6,'4 16 36',[1,2,11,50,99,1000],constraints='1 <= n <= 1000.')
l2(27,'Prime Pattern','For each prime p <= n, print a row containing p space-separated asterisks.',"for p in range(2,n+1):\n    if prime(p):print(' '.join('*'*p))",6,'* *\n* * *\n* * * * *',[1,2,3,10,20,50],constraints='1 <= n <= 100.',note='A space follows each asterisk in the source instruction; trailing spaces are optional.')
l2(28,'LCM Finder','Find the LCM. If either input is negative print Negative Input. LCM with zero is zero.',"a,b=map(int,tokens)\nprint('Negative Input' if min(a,b)<0 else math.lcm(a,b))",'12 18',36,['12 14','-2 3','0 5','7 7','17 19','1000 999','0 0'],prefix='',fmt='Two integers a and b.',constraints='-100000 <= a,b <= 100000.')
l2(29,'The Perfect Number Detective','If n is perfect, print its largest proper divisor. Otherwise print n.',"d=divisors(n)\nprint(max(d) if d and sum(d)==n else n)",6,3,[1,10,28,496,8128,10000],constraints='1 <= n <= 10000.')
l2(30,'Handshake Simulation Program','Each pair of people shakes hands once. Print the total handshakes.',"print(n*(n-1)//2)",6,15,[0,1,2,10,100,100000],constraints='0 <= n <= 100000.')
l2(31,'Odd or Even Numbers Series','Print positive integers <= n with the same parity as n. For n <= 0 print Not a Positive integer.',"if n<=0:print('Not a Positive integer')\nelse:emit(range(1 if n%2 else 2,n+1,2))",9,'1 3 5 7 9',[0,-5,1,2,4,1000],constraints='-100 <= n <= 1000.')
l2(32,'Digit Summation','Repeatedly sum the digits of the absolute value until one digit remains.',"n=abs(n)\nwhile n>=10:n=sum(map(int,str(n)))\nprint(n)",9876,3,[0,9,12345,-999,1000000000,9999999999],constraints='Absolute value has at most 10 digits.')
l2(33,'Vowel Counter','Count a,e,i,o,u in a word, case-insensitively.',"print(sum(c.lower() in 'aeiou' for c in raw))",'Bestfriends',3,['Heelloo','AEIOU','rhythm','a','education','a'*1000],prefix='',fmt='One non-empty word.',constraints='1 <= word length <= 1000.')
l2(34,'Digit Incrementer','Increment each digit; 9 wraps to 0. Output the resulting integer without leading zeros.',"print(int(''.join(str((int(c)+1)%10) for c in str(n))))",9876,987,[0,9,99,245,909,1234567890],constraints='0 <= n <= 2147483647.')
l2(35,'Printing Pattern in Reverse Order','Print rows 1..n, then 1..n-1, down to 1. For n <= 0 print Invalid Input.',"if n<=0:print('Invalid Input')\nelse:\n    for i in range(n,0,-1):emit(range(1,i+1))",3,'1 2 3\n1 2\n1',[0,-3,1,2,4,30],constraints='-100 <= n <= 50.',note='Follow the sample: row values ascend; row lengths decrease.')
l2(36,'The Odd Factorial Quest','Multiply all odd integers from 1 through n. For n < 1 print Invalid; for positive even n print Please enter a valid odd number.',"print('Invalid' if n<1 else 'Please enter a valid odd number' if n%2==0 else math.prod(range(1,n+1,2)))",5,15,[-3,0,1,6,9,19],constraints='-100 <= n <= 19.')
l2(37,'Series Expansion','Sum n terms of 1 - x^2/2! + x^4/4! - ... and print two decimal places.',"x=float(tokens[0]);n=int(tokens[1])\nprint(f'{sum((-1)**i*x**(2*i)/math.factorial(2*i) for i in range(n)):.2f}')",'7 5','56.12',['4 7','0 1','1 1','-2 5','2 8','0.5 6'],prefix='',fmt='Real x followed by integer n.',constraints='-10 <= x <= 10; 1 <= n <= 15.')
l2(38,'Fibonacci Even Number Generator','Print even Fibonacci values <= n, including zero. For n <= 0 print Invalid.',"if n<=0:print('Invalid')\nelse:\n    a,b=0,1;r=[]\n    while a<=n:\n        if a%2==0:r.append(a)\n        a,b=b,a+b\n    emit(r)",5,'0 2',[0,-2,1,2,34,150,11000])
l2(39,'Exploring the Growth Series','Print n terms starting from a, doubling each time.',"n,a=map(int,tokens)\nemit(a*2**i for i in range(n))",'5 3','3 6 12 24 48',['1 7','4 2','6 11','5 0','4 -2','20 1'],prefix='',fmt='Number of terms n, then initial term a.',constraints='1 <= n <= 30; -1000 <= a <= 1000.')
l2(40,'Sum of All Prime Factors','Sum prime factors with multiplicity. For example, 28 = 2*2*7 has sum 11.',"s=0;d=2\nwhile d*d<=n:\n    while n%d==0:s+=d;n//=d\n    d+=1\nprint(s+(n if n>1 else 0))",28,11,[1,2,85,102,160,100000],constraints='1 <= n <= 1000000.')
l2(41,'Sum of N Odd Natural Numbers','Print the first n positive odd integers, then their sum.',"emit(range(1,2*n,2))\nprint(n*n)",5,'1 3 5 7 9\n25',[1,2,7,10,50,1000],constraints='1 <= n <= 1000.')
l2(42,'Check Second Even Number','If both endpoints are even, print the second even integer in the inclusive range. Otherwise print "a and b are not Even.". If both are even but the range contains fewer than two evens, print Invalid range.',"a,b=map(int,tokens)\nprint(f'{a} and {b} are not Even.' if a%2 or b%2 else 'Invalid range' if b<a+2 else a+2)",'14 20',16,['15 41','16 40','2 4','2 2','8 2','2 9','-4 0'],prefix='',fmt='Two integer endpoints a and b.',constraints='-100000 <= a,b <= 100000.')
l2(43,"Floyd's Triangle",'Print consecutive integers in rows of length 1 to n. For n <= 0 print Invalid.',floyd,4,'1\n2 3\n4 5 6\n7 8 9 10',[0,-2,1,2,8,30],constraints='-100 <= n <= 50.')
l2(44,'Automorphic Number','Check whether the decimal representation of n squared ends in the digits of n.',"print(f'{n} is an Automorphic Number.' if str(n*n).endswith(str(n)) else f'{n} is not an Automorphic Number.')",25,'25 is an Automorphic Number.',[0,1,15,76,376,625,1000],constraints='0 <= n <= 1000000.')
l2(45,'Sum of First and Last Digit','Sum the first and last digits of the absolute value. For a single digit, count it twice.',"s=str(abs(n));print(int(s[0])+int(s[-1]))",12345,6,[0,7,-78956,1000,9999,45623],constraints='Absolute value has at most 10 digits.')
l2(46,'Sum of Even Numbers','Sum even positive integers <= n. For n <= 0 print "n is an Invalid number.".',"print((n//2)*(n//2+1) if n>0 else f'{n} is an Invalid number.')",20,110,[0,-12,1,2,7,100000])
l2(47,'XOR Operations — Collatz Steps','Count steps until n becomes 1: divide even values by 2; replace odd values with 3*n+1.',"c=0\nwhile n!=1:\n    n=n//2 if n%2==0 else 3*n+1;c+=1\nprint(c)",6,8,[1,2,25,27,97,100000],constraints='1 <= n <= 100000.',note='The PDF describes Collatz steps. Its XOR-only restriction is inconsistent with the task; this judge checks the output, not which operators you use.')
l2(48,'Sum of the Middle Digits','Sum digits excluding the first and last, ignoring a minus sign. Numbers with fewer than three digits have sum zero.',"print(sum(map(int,str(abs(n))[1:-1])))",14562,15,[0,7,12,789,-10254823,10000001],constraints='Absolute value has at most 10 digits.')
l2(49,'Reverse the Digits','Truncate any fractional part towards zero, then reverse digits and discard leading zeros. For a negative truncated integer print "n is not a Positive Number.". Zero gives zero.',"print(f'{n} is not a Positive Number.' if n<0 else int(str(n)[::-1]))",'00710.823',17,['96387','0','-52','78.36921','1000','29876.235'],prefix='n=int(float(tokens[0]))\n',fmt='One numeric value, optionally with a fractional part.',constraints='-1000000000 <= input <= 1000000000.')
l2(50,'Perfect Square','Truncate any fractional part towards zero. Check whether n is a perfect square. For negative n print "n is Invalid Number.".',"print(f'{n} is Invalid Number.' if n<0 else f'{n} is a Perfect Square.' if math.isqrt(n)**2==n else f'{n} is not a Perfect Square.')",'16.00','16 is a Perfect Square.',['02.53','-26.399','0','1','400.5','785'],prefix='n=int(float(tokens[0]))\n',fmt='One numeric value, optionally with a fractional part.',constraints='-1000000000 <= input <= 1000000000.')
l2(51,'Alphabetical Pattern','Print A, AB, ABC, ... for n rows. For n outside 1..26 print "n is an Invalid input.".',"print('\\n'.join('ABCDEFGHIJKLMNOPQRSTUVWXYZ'[:i] for i in range(1,n+1)) if 1<=n<=26 else f'{n} is an Invalid input.')",3,'A\nAB\nABC',[0,-10,1,5,26,27])
l2(52,'Multiples of 5 — Pattern Printing','Row i contains the first i multiples of 5. For n < 1 print "n is an Invalid input.".',mult.replace("else 'Invalid'","else f'{n} is an Invalid input.'"),3,'5\n5 10\n5 10 15',[0,-35,1,2,6,30],constraints='-100 <= n <= 50.')
l2(53,'Product of N Digits','Multiply the decimal digits of n. If the product is zero, print Invalid Input.',"p=math.prod(map(int,str(n)))\nprint(p if p else 'Invalid Input.')",1258,80,[0,1,12508,453789,111111,999999999],constraints='0 <= n <= 999999999.')
l2(54,'Prime Numbers in a Range','Print all primes in the inclusive range [a,b] in increasing order. If none exist print an empty line.',"a,b=map(int,tokens)\nemit(x for x in range(a,b+1) if prime(x))",'10 25','11 13 17 19 23',['2 5','1 1','-5 3','10 2','67 95','1000 1100'],prefix='',fmt='Two integer endpoints a and b.',constraints='-100 <= a,b <= 100000.')
l2(55,'Harshad Number','Check whether positive integer n is divisible by its digit sum.',"print(f'{n} is Harshad number.' if n%sum(map(int,str(n)))==0 else f'{n} is Not Harshad number.')",18,'18 is Harshad number.',[1,99,24,25,51,100000],constraints='1 <= n <= 1000000.')
l2(56,'Strong Number','Check whether n equals the sum of the factorials of its decimal digits.',"print(f'{n} is a Strong Number.' if sum(math.factorial(int(c)) for c in str(n))==n else f'{n} is Not a Strong Number.')",1,'1 is a Strong Number.',[0,2,145,4534,40585,99999],constraints='0 <= n <= 1000000.')
l2(57,'Palindrome Check','Convert to absolute value, then check whether digits read the same backwards. Print "n is a Palindrome." or "n is Not a Palindrome." using the absolute value.',"n=abs(n)\nprint(f'{n} is a Palindrome.' if str(n)==str(n)[::-1] else f'{n} is Not a Palindrome.')",121,'121 is a Palindrome.',[0,-121,33233,3214,10,9999999],constraints='Absolute value has at most 10 digits.',note='Use "is a Palindrome" consistently; one PDF example omits "a".')
# Array contracts: whitespace-separated output, explicit indexing, stable order.
ARRAY='n=int(tokens[0])\na=list(map(int,tokens[1:1+n]))\ntail=list(map(int,tokens[1+n:]))\n'
def arr(a,*tail):return str(len(a))+'\n'+' '.join(map(str,a))+('\n'+' '.join(map(str,tail)) if tail else '')
standard=[[7],[0,0,0],[-5,-1,-9],[3,1,3,2,1],[1,2,3,4,5],list(range(99,-1,-1))]
def l3(n,title,desc,body,sample,expected,cases=None,**kw):
    kw.setdefault('prefix',ARRAY);kw.setdefault('fmt','Integer n, followed by n integers. Read across any whitespace.')
    kw.setdefault('constraints','1 <= n <= 100; -1000 <= array values <= 1000.')
    kw.setdefault('outfmt','Separate array values by spaces. Print no prompts, brackets, or commas unless specified. An empty result is an empty line.')
    add(3,n,title,desc,body,sample,expected,cases if cases is not None else [arr(a) for a in standard],**kw)
l3(1,'Average of an Array','Read exactly five integers. Print their integer average, truncating towards zero.',"a=list(map(int,tokens));print(math.trunc(sum(a)/5))",'5 8 9 6 3',6,['0 0 0 0 0','1 2 3 4 5','-1 -2 -3 -4 -6','1 1 1 1 2','1000 1000 1000 1000 1000','-10 0 10 0 0'],prefix='',fmt='Exactly five integers; no size prefix.',constraints='-1000 <= each of five values <= 1000.',note='The supplied answer fixes n=5 and uses integer division.')
l3(2,'Finding the Maximum Number','Print the largest array value.',"print(max(a))",arr([2,52,86,489,21]),489)
l3(3,'Peak Elements','A peak is at least as large as its existing neighbors. Print the first endpoint if a peak, then the last endpoint if a peak, then internal peaks from left to right. A singleton is printed once.',"if n==1:emit(a)\nelse:\n    r=([a[0]] if a[0]>=a[1] else [])+([a[-1]] if a[-1]>=a[-2] else [])\n    r += [a[i] for i in range(1,n-1) if a[i]>=a[i-1] and a[i]>=a[i+1]]\n    emit(r)",arr([7,6,5,6,7,9]),'7 9',note='Endpoint-first ordering matches the answer code; equal neighbors qualify.')
rotcases=[arr([1],0),arr([1,2,3],0),arr([1,2,3],3),arr([1,2,3],8),arr([-2,0,2,2],1),arr(list(range(100)),100001)]
l3(4,'Left Rotation','Rotate the array left by k positions; k may exceed n.',"k=tail[0]%n;emit(a[k:]+a[:k])",arr([7,8,9,6,3],1),'8 9 6 3 7',rotcases,fmt='n, n array values, then k.',constraints='1 <= n <= 100; -1000 <= values <= 1000; 0 <= k <= 1000000.')
l3(5,'Right Rotation','Rotate the array right by k positions; k may exceed n.',"k=tail[0]%n;emit(a[-k:]+a[:-k] if k else a)",arr([7,4,1,2,5],1),'5 7 4 1 2',rotcases,fmt='n, n array values, then k.',constraints='1 <= n <= 100; -1000 <= values <= 1000; 0 <= k <= 1000000.')
targetcases=[arr([7],7),arr([0,0,0],0),arr([-5,-1,-5],-5),arr([1,2,3],9),arr([4,2,4,4],4),arr(list(range(100)),99)]
l3(6,'Number of Occurrences','Count the occurrences of target x.',"print(a.count(tail[0]))",arr([4,8,9,6,8,5,7,6],8),2,targetcases,fmt='n, n array values, then target x.')
productcases=[arr([7]),arr([0,2,3]),arr([-2,3,-4]),arr([1]*100),arr([2]*20),arr([-1,1,-1,1])]
l3(7,'Sum and Product of an Array','Print the sum on the first line and product on the second.',"print(sum(a));print(math.prod(a))",arr([4,8,5,2,3,1]),'23\n960',productcases,constraints='1 <= n <= 100; -1000 <= values <= 1000; all intermediate products fit signed 64-bit integers.')
l3(8,'Square of Array Elements','Print the square of each element, preserving order.',"emit(x*x for x in a)",arr([4,2,6,3,2]),'16 4 36 9 4')
l3(9,'Difference Between Maximum and Minimum','Print maximum and minimum on the first line; print maximum minus minimum on the next.',"print(max(a),min(a));print(max(a)-min(a))",arr([78,96,52,41,23]),'96 23\n73')
l3(10,'Elements Divisible by a Number','Count values divisible by divisor d. If d is zero print Invalid.',"d=tail[0];print(sum(x%d==0 for x in a) if d else 'Invalid')",arr([7,8,9,6,5],2),2,[arr([0],2),arr([1,2,3],1),arr([-4,0,5],-2),arr([7,9],2),arr([1,2],0),arr(list(range(100)),3)],fmt='n, n array values, then divisor d.')
l3(11,'Removing Duplicate Elements — Keep Last','Keep only the last occurrence of each value, preserving their relative order.',"emit(x for i,x in enumerate(a) if x not in a[i+1:])",arr([4,2,5,4,3]),'2 5 4 3',note='Unlike question 28, this answer keeps the last occurrence.')
l3(12,'Negative Elements','Print only values strictly less than zero.',"emit(x for x in a if x<0)",arr([7,8,-5,-6,2,4]),'-5 -6')
l3(13,'Positive Elements','Print only values strictly greater than zero.',"emit(x for x in a if x>0)",arr([7,8,5,-2,-3,6]),'7 8 5 6')
l3(14,'Delete an Element at a Position','Delete the value at the 1-based position p. For p outside 1..n print Invalid.',"p=tail[0]\nif 1<=p<=n:emit(a[:p-1]+a[p:])\nelse:print('Invalid')",arr([7,9,6,3,2],3),'7 9 3 2',[arr([7],1),arr([1,2,3],1),arr([1,2,3],3),arr([1,2,3],0),arr([1,2,3],4),arr(list(range(100)),50)],fmt='n, n values, then 1-based position p.')
l3(15,'Sum of Duplicate Elements','Print each occurrence which has another equal value later in the array. Then print the sum of those printed occurrences.',"r=[x for i,x in enumerate(a) if x in a[i+1:]]\nemit(r);print(sum(r))",arr([7,9,6,8,7,9]),'7 9\n16',note='For [2,2,2], print 2 2 then sum 4. This follows the supplied answer rather than summing each repeated value once.')
l3(16,'Non-Prime Numbers','Print composite integers in the array (integers >1 which are not prime).',"emit(x for x in a if x>1 and not prime(x))",arr([7,6,3,22,5,86,20,13]),'6 22 86 20',note='The supplied code excludes 0,1 and negative values, so this exercise uses composite numbers.')
l3(17,'Sum of First, Second, Last and Penultimate','Sum the first two and last two elements. There are at least four elements.',"print(a[0]+a[1]+a[-1]+a[-2])",arr([7,8,9,6,3]),24,[arr([1,2,3,4]),arr([0]*4),arr([-1,-2,-3,-4]),arr([2]*8),arr([1,2,100,4,5]),arr(list(range(100)))],constraints='4 <= n <= 100; -1000 <= values <= 1000.')
l3(18,'Printing Unique Numbers','Print elements whose frequency is exactly one, in original order.',"c=Counter(a);emit(x for x in a if c[x]==1)",arr([7,6,3,8,9,7,3,5]),'6 8 9 5')
l3(19,'Second Largest Number','Print the second largest distinct value. If fewer than two distinct values exist print Not found.',"s=sorted(set(a));print(s[-2] if len(s)>1 else 'Not found')",arr([77,96,85,12,425,525]),425,note='Fixes the source initialization bug when the first element is already the largest.')
l3(20,'Ascending Order','Sort the array in nondecreasing order.',"emit(sorted(a))",arr([12,63,85,96,41,56]),'12 41 56 63 85 96')
l3(21,'Removing Even Numbers','Remove every even number, preserving odd values in order.',"emit(x for x in a if x%2)",arr([7,8,9,6,2]),'7 9')
remove="x=tail[0]\nif x in a:a.remove(x)\nemit(a)"
l3(22,'Removing First Occurrence','Remove only the first occurrence of x. If absent, leave the array unchanged.',remove,arr([7,8,9,7,5,2],7),'8 9 7 5 2',targetcases,fmt='n, n array values, then x.',note='Fixes the source code dropping the last element when x is absent.')
l3(23,'Pair with Sum Closest to Zero','For array length outside 2..10 print Invalid. Otherwise choose distinct indices i<j minimizing abs(a[i]+a[j]). Ties choose the smallest i, then smallest j. Print the two values.',"if not 2<=n<=10:print('Invalid')\nelse:\n    i,j=min(((i,j) for i in range(n) for j in range(i+1,n)),key=lambda ij:(abs(a[ij[0]]+a[ij[1]]),ij))\n    print(a[i],a[j])",arr([-1,-10,8,2]),'-1 2',[arr([1]),arr(list(range(11))),arr([-5,5]),arr([1,2,3]),arr([-8,-2,-1]),arr([-2,2,-1,1]),arr([0,0,5])],constraints='0 <= n <= 100; -1000 <= values <= 1000.',note='The 2..10 restriction is applied to length. Applying it to values would contradict the PDF example with -10 and -1.')
l3(24,'Median','Print the sorted array, then its median to six decimal places. For even length take the arithmetic mean of the two middle values.',"a.sort();emit(a);print(f'{(a[n//2] if n%2 else (a[n//2-1]+a[n//2])/2):.6f}')",arr([7,8,9,64,21,32]),'7 8 9 21 32 64\n15.000000',[arr([1,2]),arr([7]),arr([-3,-2]),arr([3,1,2]),arr([2,2,2,2]),arr(list(range(100)))],note='Fractional medians are preserved; the source accidentally uses integer division.')
l3(25,'Chunk Size','Split the array into consecutive chunks of at most k elements. Print adjacent bracketed comma-separated chunks with no spaces, e.g. [1,2][3]. For k <= 0 print Invalid.',"k=tail[0]\nprint(''.join('['+','.join(map(str,a[i:i+k]))+']' for i in range(0,n,k)) if k>0 else 'Invalid')",arr([10,52,85,63,41],2),'[10,52][85,63][41]',[arr([7],1),arr([1,2,3],1),arr([1,2,3],3),arr([1,2,3],5),arr([1,2],0),arr([1,2],-1),arr(list(range(100)),9)],fmt='n, n values, then chunk size k.')
l3(26,'Insert at a Particular Position','Insert value x at 1-based position p (1..n+1). If p is invalid print Invalid.',"x,p=tail\nif 1<=p<=n+1:a.insert(p-1,x);emit(a)\nelse:print('Invalid')",arr([1,4,7,8,5],2,3),'1 4 2 7 8 5',[arr([7],9,1),arr([7],9,2),arr([1,2,3],0,2),arr([1,2],5,0),arr([1,2],5,4),arr(list(range(100)),1000,101)],fmt='n, n values, then value x and 1-based position p.')
l3(27,'Frequency of Elements','Print each distinct value followed by its frequency, one pair per line, in order of first appearance.',"for x,c in Counter(a).items():print(x,c)",arr([1,5,2,1,4,2]),'1 2\n5 1\n2 2\n4 1')
l3(28,'Deleting Duplicates — Keep First','Keep the first occurrence of each value and delete later occurrences.',"emit(dict.fromkeys(a))",arr([10,20,10,1,100,10,2,1,5,10]),'10 20 1 100 2 5')
l3(29,'Merge Two Arrays and Sort','Merge both arrays and sort all elements in nondecreasing order; retain duplicates.',"n,m=map(int,tokens[:2]);a=list(map(int,tokens[2:]));emit(sorted(a))",'5 4\n7 8 9 6 22\n14 25 36 78','6 7 8 9 14 22 25 36 78',['1 1\n1\n2','2 2\n0 0\n0 0','2 3\n-5 -1\n-2 0 3','0 2\n1 2','2 0\n4 3','3 3\n3 2 1\n6 5 4'],prefix='',fmt='Sizes n and m first, then n values of the first array and m values of the second.',constraints='0 <= n,m <= 100; n+m >= 1; -1000 <= values <= 1000.')
l3(30,'Reverse Array Elements','Print elements in reverse order.',"emit(a[::-1])",arr([78,52,63,14,12]),'12 14 63 52 78')
l3(31,'Even and Odd Numbers in Separate Arrays','Print even values on the first line and odd values on the second, each preserving input order.',"emit(x for x in a if x%2==0);emit(x for x in a if x%2)",arr([11,25,36,45,88]),'36 88\n11 25 45')
l3(32,'Search an Element and Print Its Position','Print the 1-based position of the first occurrence of x, or -1 if absent.',"print(a.index(tail[0])+1 if tail[0] in a else -1)",arr([11,22,33,44,55,66],55),5,targetcases,fmt='n, n array values, then x.')
l3(33,'Even-Odd Partition and Sorted Array','Print even values followed by odd values, preserving order within each group, on the first line. Print the fully sorted original array on the second.',"emit([x for x in a if x%2==0]+[x for x in a if x%2]);emit(sorted(a))",arr([11,22,55,66,33,44]),'22 66 44 11 55 33\n11 22 33 44 55 66',note='The PDF labels this question only "33."; its two answer screenshots define this operation.')
firstpair="target=tail[0]\nr=[(i,j) for i in range(n) for j in range(i+1,n) if a[i]+a[j]==target]\nif r:print(*r[0])\nelse:print('NOT FOUND')"
paircases=[arr([1,2],3),arr([1,2],4),arr([0,0,0],0),arr([-5,2,5,8],3),arr([3,3,3,3],6),arr(list(range(100)),197)]
l3(34,'Find a Pair with a Given Sum','Print zero-based indices of the first pair i<j summing to target (smallest i, then j). Print NOT FOUND if no pair exists.',firstpair,arr([14,12,36,52,15],64),'1 3',paircases,fmt='n, n values, then target.',note='The screenshot prints indices rather than values.')
l3(35,'Removing First Occurrence — Practice','Remove only the first occurrence of x, preserving all other values. If absent, return the original array.',remove,arr([1,4,8,5,1,4],4),'1 8 5 1 4',targetcases,fmt='n, n values, then x.')
l3(36,'Sum of Neighbor Peak Elements','Replace each peak with itself plus its existing immediate neighbors. A peak is >= every existing neighbor. Determine all peaks and sums from the original array, simultaneously. Non-peaks stay unchanged.',"r=a.copy()\nfor i,x in enumerate(a):\n    neighbors=a[max(0,i-1):i]+a[i+1:i+2]\n    if all(x>=v for v in neighbors):r[i]=x+sum(neighbors)\nemit(r)",arr([7,4,5,2,1,8]),'11 4 11 2 1 9',note='The source reads outside array bounds and modifies values while detecting peaks. This contract uses existing neighbors and simultaneous updates to make results deterministic.')
l3(37,'Swapping Two Elements','Swap values at zero-based indices i and j. If either index is outside 0..n-1 print Invalid.',"i,j=tail\nif 0<=i<n and 0<=j<n:a[i],a[j]=a[j],a[i];emit(a)\nelse:print('Invalid')",arr([1,2,3,4,5],3,2),'1 2 4 3 5',[arr([7],0,0),arr([1,2],0,1),arr([1,2],-1,1),arr([1,2],0,2),arr([3,3,2],0,2),arr(list(range(100)),0,99)],fmt='n, n values, then zero-based indices i and j.')
l3(38,'Sorted or Not Sorted','An array is sorted if nondecreasing OR nonincreasing; equality is allowed. Print array is sorted or array is not sorted.',"print('array is sorted' if a==sorted(a) or a==sorted(a,reverse=True) else 'array is not sorted')",arr([11,12,13,14,15,16]),'array is sorted')
l3(39,'Sort Even Numbers First, Odd Numbers Next','Sort the even values ascending, then the odd values ascending; print both groups on one line.',"emit(sorted((x for x in a if x%2==0))+sorted(x for x in a if x%2))",arr([1,7,8,5,9,6]),'6 8 1 5 7 9')
l3(40,'Remove All Occurrences of a Value','Remove every array element equal to x, including adjacent occurrences.',"emit(v for v in a if v!=tail[0])",arr([7,8,5,2,5,1],5),'7 8 2 1',targetcases,fmt='n, n values, then x.',note='This removes whole elements, not digits within multi-digit integers.')
l3(41,'Product of Array Except Self','For each position print the product of every other element. Do not divide by the current value. The empty product for a singleton is 1.',"emit(math.prod(a[:i]+a[i+1:]) for i in range(n))",arr([1,2,3,4,5]),'120 60 40 30 24',productcases+[arr([0,0,2])],constraints='1 <= n <= 100; -1000 <= values <= 1000; products fit signed 64-bit integers.')
l3(42,'Numbers Smaller Than the Current Number','For every element count array entries strictly smaller than it.',"emit(sum(y<x for y in a) for x in a)",arr([8,1,2,2,3]),'4 0 1 1 3')
l3(43,'Ranking','Rank each element as 1 plus the number of array entries strictly smaller than it. Equal values share ranks; ranks may have gaps.',"emit(1+sum(y<x for y in a) for x in a)",arr([52,41,63,95,35]),'3 2 4 5 1',note='Uses competition ranking, not dense ranking: [10,10,20] gives [1,1,3].')
l3(44,'Remove Even Numbers at Even Indices','Remove elements that are even AND located at an even zero-based index in the original array (including index 0). Retained elements keep their order.',"emit(x for i,x in enumerate(a) if not(i%2==0 and x%2==0))",arr([4,9,8,6,2,1]),'9 6 1',note='The source starts at index 2 and shifts indices during deletion. This corrected contract uses original zero-based indices consistently.')
l3(45,'Remove Elements Greater Than a Number','Remove values strictly greater than x. Values equal to x remain.',"emit(v for v in a if v<=tail[0])",arr([25,36,14,85,96,45],40),'25 36 14',targetcases,fmt='n, n values, then threshold x.',note='Follows the question heading; the screenshot uses < and accidentally also removes equal values.')
l3(46,'Last Repeated Element','Among values appearing at least twice, print the one whose last occurrence is farthest right. If none repeat print no elements duplicate.',"c=Counter(a);r=[x for x in a if c[x]>1];print(r[-1] if r else 'no elements duplicate')",arr([7,5,3,6,2,5,7,8]),7)
l3(47,'Array Leaders in Ascending Order','A leader is strictly greater than every element to its right. The last element is always a leader. Print leaders in ascending order.',"r=[];largest=None\nfor x in reversed(a):\n    if largest is None or x>largest:r.append(x);largest=x\nemit(r)",arr([5,3,20,15,8]),'8 15 20')
l3(48,'Maximum Subarray Sum','Find the maximum sum of a non-empty contiguous subarray. For an all-negative array return its largest value.',"best=cur=a[0]\nfor x in a[1:]:cur=max(x,cur+x);best=max(best,cur)\nprint(best)",arr([-2,1,-3,4,-1,2,1,-5,4]),6,note='The source code repeats arr[i] instead of summing a subarray and shows 42 for [7,8,9,6,5,4]. This corrected maximum-subarray problem gives 39 for that array.')
l3(49,'Sum of Non-Repeated Numbers','Sum values which occur exactly once. If none exist print 0.',"c=Counter(a);print(sum(x for x in a if c[x]==1))",arr([7,8,9,5,7,8]),14)
l3(50,'Left Character Rotation','Rotate a word left by k characters, preserving case. Reduce k modulo the word length.',"s=tokens[0];k=int(tokens[1])%len(s);print(s[k:]+s[:k])",'abcdef 2','cdefab',['a 0','abc 0','abc 3','abc 7','AaBb 1','hello 100'],prefix='',fmt='One word followed by a nonnegative rotation count k.',constraints='1 <= word length <= 1000; 0 <= k <= 1000000.',note='The PDF supplies only a heading for this question; this input/output contract completes it.')
l3(51,'Indices of All Pairs with Target Sum','Print all zero-based index pairs i<j whose values sum to target, ordered by i then j. Print each pair on its own line. If no pairs exist print NOT FOUND.',"target=tail[0];r=[(i,j) for i in range(n) for j in range(i+1,n) if a[i]+a[j]==target]\nif not r:print('NOT FOUND')\nfor pair in r:print(*pair)",arr([7,8,5,2,3,1],13),'1 2',paircases,fmt='n, n values, then target.')
l3(52,'Converting Angle to Radians','Convert degrees to radians using pi. Print "Angle in radians: " followed by the value to two decimal places.',"print(f'Angle in radians: {float(tokens[0])*math.pi/180:.2f}')",145,'Angle in radians: 2.53',[0,90,180,360,-90,45.5,720],prefix='',fmt='One real-valued angle in degrees.',constraints='-100000 <= degrees <= 100000.')

assert len(problems)==109
assert len({p['slug'] for p in problems})==109
out=ROOT/'backend/src/catalog/problems.json';out.parent.mkdir(parents=True,exist_ok=True)
out.write_text(json.dumps(problems,indent=2,ensure_ascii=False)+'\n')
notes=['# PDF question catalog','', 'All 57 Level 2 questions and all 52 Level 3 questions are included. Original numbering is shown in each description. Platform numbers 1–57 are Level 2; 58–109 are Level 3. Existing problem IDs/slugs are preserved by seeding.','', 'Each reference is checked against a hand-entered example. Deterministic hidden inputs cover edge cases and larger values. These are hidden from the student API, not secret from repository owners. Do not publish the backend catalog if test secrecy from source readers is required.','', '## Judging conventions','', 'Read stdin without interactive prompts. Array outputs use spaces, not concatenated digits. Line breaks distinguish output sections and pattern rows. Trailing whitespace is ignored. C/C++ solutions should use 64-bit integers where constraints require them; Java solutions use Main. No language receives starter code.','', '## Source ambiguities and corrections','']
for p in problems:
 if 'Clarification:' in p['description']:notes.append(f"- **{p['source']} Q{p['source_number']} — {p['title']}:** "+p['description'].split('Clarification: ')[1])
notes+=['','## Complete mapping','','| PDF | Question | Platform # | Title | Hidden cases |','|---|---:|---:|---|---:|']
for p in problems:notes.append(f"| {p['source']} | {p['source_number']} | {p['problem_number']} | {p['title']} | {sum(t['is_hidden'] for t in p['tests'])} |")
(ROOT/'docs').mkdir(exist_ok=True);(ROOT/'docs/pdf-catalog.md').write_text('\n'.join(notes)+'\n')
print(f"Built {len(problems)} problems, {sum(len(p['tests']) for p in problems)} cases, {sum(t['is_hidden'] for p in problems for t in p['tests'])} hidden; all 109 anchor examples passed.")
